meta_product_name: "Social Games"
meta_title: "SocialGames, Be Social, Stay FIT, play without the hassel"
meta_description: "We are a casual fitness platform that covers your need of socialization and fitness without the commitment. Play on!"
meta_image: "front2.png" 