meta_product_name: "Social Games"
meta_title: "Social Games, Be Social, Stay Fit, play with flexibility"
meta_description: "We are a casual fitness platform that covers your need of socialisation and fitness without the commitment. Play on!"
meta_image: "front2.png" 